real_estate_site/urls.py
from django.contrib import admin
from django.urls import path, include
from shop import urls as shop_urls
from . import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('shop/', include((shop_urls, 'shop'), namespace='shop')),
]


if settings.DEBUG:
    from django.contrib.staticfiles.urls import static
    from django.contrib.staticfiles.urls import staticfiles_urlpatterns
    urlpatterns += staticfiles_urlpatterns()
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/urls.py
from django.urls import path

from . import views


app_name = 'shop'

urlpatterns = [
    # ex: /shop/
    path('', views.index, name='ProductList'),
    # ex: /shop/5/
    path('<int:product_id>/', views.product_detail_view, name='ProductDetail'),
]

shop/models.py
import os
import requests

from django.db import models
from django.urls import reverse
from django_google_maps import fields as map_fields
from django.dispatch.dispatcher import receiver

from real_estate_site import settings


# Create your models here.
class Product(models.Model):
    title = models.CharField(
        max_length=120,
        verbose_name="Заголовок",
    )
    about = models.TextField(
        blank=True,
        verbose_name="Додаткова інформація",
    )
    pub_date = models.DateTimeField(
        auto_now_add=True,
        blank=True,
        verbose_name='Дата публікації',
    )

    OBJECT_TYPE__CHOICES = (
        ("land", "Земля"),
        ("object", "Об'єкт нерухомості"),
    )
    object_type = models.CharField(
        max_length=20,
        choices=OBJECT_TYPE__CHOICES,
        verbose_name="Тип об'єкту",
    )

    OFFER_TYPE__CHOICES = (
        ("rent", "Оренда"),
        ("sale", "Продаж"),
    )
    offer_type = models.CharField(
        max_length=20,
        choices=OFFER_TYPE__CHOICES,
        verbose_name='Тип пропозиції',
    )

    price = models.DecimalField(
        max_digits=6,
        decimal_places=0,
        blank=True,
        null=True,
        verbose_name='Ціна',
    )
    CURRENCY_TYPE__CHOICES = (
        ("UAH", "₴"),
        ("USD", "$"),
        ("EUR", "€"),
    )
    currency_type = models.CharField(
        max_length=20,
        choices=CURRENCY_TYPE__CHOICES,
        default=CURRENCY_TYPE__CHOICES[0],
        verbose_name='Грошова одиниця'
    )

    area = models.DecimalField(
        max_digits=6,
        decimal_places=2,
        blank=False,
        null=False,
        verbose_name='Площа')
    AREA_UNIT_TYPE__CHOICES = (
        ("m2", "М²"),
        ("ha", "Га"),
        ("a", "А"),
    )
    area_unit_type = models.CharField(
        max_length=20,
        choices=AREA_UNIT_TYPE__CHOICES,
        default=AREA_UNIT_TYPE__CHOICES[0],
        verbose_name='Величина вимірювання'
    )

    city = models.ForeignKey(
        to='cities_light.City',
        help_text="City Foreign Key",
        on_delete=models.PROTECT,
        verbose_name='Місто',
    )
    region = models.ForeignKey(
        to='cities_light.Region',
        help_text="Region Foreign Key",
        on_delete=models.PROTECT,
        verbose_name='Область',
    )

    city_detail = models.CharField(
        blank=True,
        max_length=120,
        verbose_name='Місто'
    )

    region_detail = models.CharField(
        blank=True,
        max_length=120,
        verbose_name='Область'
    )

    district_detail = models.CharField(
        blank=True,
        max_length=120,
        verbose_name='Район'
    )

    street_detail = models.CharField(
        blank=True,
        max_length=120,
        verbose_name='Вулиця'
    )
    street_number_detail = models.CharField(
        blank=True,
        max_length=20,
        verbose_name='Номер будинку'
    )

    address = map_fields.AddressField(
        max_length=200,
        blank=True,
        verbose_name='Адреса'
    )
    geolocation = map_fields.GeoLocationField(
        max_length=100,
        blank=True,
        verbose_name='Місце на карті',
    )

    def save(self, *args, **kwargs):
        # Use Google's reverse geocoder directly by url
        base = "https://maps.googleapis.com/maps/api/geocode/json?"
        params = "address={address}".format(
            address=self.address,
        )
        key = settings.GOOGLE_MAPS_API_KEY
        languages = "uk"
        url = "{base}{params}&key=%20{key}&language={language}".format(
            base=base,
            params=params,
            key=key,
            language=languages
        )
        while True:
            response = requests.get(url).json()
            if response['status'] == 'OK':
                result = response['results'][0]
                break

        for component in result['address_components']:
            if 'street_number' in component['types']:
                self.street_number_detail = component['long_name']
            if 'route' in component['types']:
                self.street_detail = component['long_name']
            if 'locality' in component['types']:
                self.city_detail = component['long_name']
            if 'administrative_area_level_1' in component['types']:
                self.region_detail = component['long_name']
            if 'administrative_area_level_2' in component['types']:
                self.district_detail = component['long_name']
        self.address = result['formatted_address']
        super().save(*args, **kwargs)  # Call the "real" save() method.

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('shop:ProductDetail', args=[str(self.id)])

    class Meta:
        ordering = ['title', 'pub_date']
        verbose_name = "Об'єкт"
        verbose_name_plural = "Об'єкти"


class Image(models.Model):
    product = models.ForeignKey(
        to=Product,
        on_delete=models.CASCADE,
        help_text="Photo Foreign Key",
        verbose_name="Об'єкт",
        related_name="images",
    )
    image = models.ImageField(
        blank=True,
        upload_to='images/shop/%Y/%m/%d',
        verbose_name='Фотографії',
    )


# These two auto-delete files from filesystem when they are unneeded:
@receiver(models.signals.post_delete, sender=Image)
def auto_delete_file_on_delete(sender, instance, **kwargs):
    """
    Deletes file from filesystem
    when corresponding `Image` object is deleted.
    """
    if instance.image:
        if os.path.isfile(instance.image.path):
            os.remove(instance.image.path)


@receiver(models.signals.pre_save, sender=Image)
def auto_delete_file_on_change(sender, instance, **kwargs):
    """
    Deletes old file from filesystem
    when corresponding `Image` object is updated
    with new file.
    """
    if not instance.pk:
        return False
    try:
        old_file = Image.objects.get(pk=instance.pk).file
    except Image.DoesNotExist:
        return False

    new_file = instance.image
    if not old_file == new_file:
        if os.path.isfile(old_file.path):
            os.remove(old_file.path)

shop/forms.py
from django import forms
from .models import Product
from django_google_maps.widgets import GoogleMapsAddressWidget


class GoogleMapForm(forms.ModelForm):

    class Meta(object):
        model = Product
        fields = ['address', 'geolocation']
        widgets = {
            "address": GoogleMapsAddressWidget(attrs={'disabled': 'disabled'}),
        }

shop/views.py
from urllib.parse import urlencode

from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.shortcuts import get_object_or_404
from django.shortcuts import render

from .models import Product
from .forms import GoogleMapForm
from .filters import ProductFilter
from account.models import Account


# Create your views here.
def index(request):
    all_products = Product.objects.all().order_by('-pub_date')
    product_filter = ProductFilter(request.GET, queryset=all_products)
    product_list = product_filter.qs
    contacts = Account.objects.all()

    paginator = Paginator(product_list, 2)
    page = request.GET.get('page', 1)

    gt = request.GET.copy()
    if 'page' in gt:
        del gt['page']

    try:
        products = paginator.page(page)
    except PageNotAnInteger:
        products = paginator.page(1)
    except EmptyPage:
        products = paginator.page(paginator.num_pages)

    return render(request, 'shop/index.html', {
        'filter': product_filter,
        'products': products,
        'contacts': contacts,
        'params': urlencode(gt),
        'page_request_var': paginator,
    })


def product_detail_view(request, product_id):
    product = get_object_or_404(Product, pk=product_id)
    form = GoogleMapForm(initial={
        'address': product.address,
        'geolocation': product.geolocation,
    })
    form.fields['geolocation'].widget.attrs['disabled'] = True
    form.fields['address'].widget.attrs['readonly'] = True
    image_models = product.images.all()
    return render(request, 'shop/product_detail.html', {
        'object': product,
        'form': form,
        "image_models": image_models,
    })


"""
class IndexProductListView(ListView):
    model = Product
    ordering = ['-pub_date']
    template_name = 'shop/index.html'

    def get_context_data(self, **kwargs):
        queryset = ''
        context = super(IndexProductListView, self).get_context_data()

        context['products'] = Product.objects.all()

        product_list = Product.objects.all()
        product_filter = ProductFilter(self.kwargs, queryset=product_list)
        context['filter'] = product_filter

        paginator = Paginator(context['products'], 3)
        page_request_var = "page"
        page = self.request.GET.get(page_request_var)
        try:
            queryset = paginator.page(page)
        except PageNotAnInteger:
            queryset = paginator.page(1)
        except EmptyPage:
            queryset = paginator.page(paginator.num_pages)

        context['products'] = queryset
        context['page_request_var'] = page_request_var
        return context
"""

shop/templates/shop/base.html
{% load static %}
<!DOCTYPE html>


<html lang="ua">
    <head>
        <meta charset="utf-8">
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="http://code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
        <link href="https://fonts.googleapis.com/css?family=Asap:400,700|Roboto:300,400,500,900" rel="stylesheet">
        <link rel="stylesheet" href="{% static 'shop/css/media.css' %}">
        <link rel="stylesheet" href="{% static 'shop/css/main.css' %}">

        <!--[if lt IE 9]>
          <script src="https://cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.3/html5shiv.js"></script>
        <![endif]-->
    </head>

    <body>
        <header>
        	<div class="topHead">
        		<div class="logo">
                    <a href='/shop'><p>SHOP</p></a>
        		</div>
        	</div>
            <div class="topHead">
                <div class="contactInfo">
                    <ul>
                        Контакти
                        {% for contact in contacts %}
                            <div class="contact">
                                <p>{{ contact.mobile_phone_number }} - {% if contact.is_online == True %}ONLINE{% else %}OFFLINE{% endif %}</p>
                            </div>
                        {% endfor %}
                    </ul>
                </div>
            </div>
        </header>
        {% block content %} {% endblock %}
    </body>
    <footer>
            <div class="footerBlock">
                <p>created by 2018</p>
            </div>
    </footer>
</html>

shop/templates/shop/index.html
{% extends 'shop/base.html' %}

{% load staticfiles %}
{% load static %}

{% block title %}
  Головна
{% endblock %}


{% block content %}



<div class="filterBlock">
    <!--
    <form method="get">
        {{ filter.form.as_p }}
        <button type="submit">Search</button>
    </form>{% csrf_token %}
    -->

    <form action="" method="get">
        {{ filter.form.as_p }}
        <input type="submit" />
    </form>

</div>

<div class="centralBook">
    <ul>
        {% for product in products %}
            <div class="productBlock">
                {% if image_models %}
                      {% for image_model in image_models %}
                          <div class="imgBlock">
                              <img src="{{ image_model.image.url }}" height="200" width="200" alt="">
                          </div>
                      {% endfor %}
                {% endif %}
                <a href={{ product.get_absolute_url }}>
                    <h3>{{ product.title }}</h3>
                </a>
                <div class="offer_type">
                    <p>{{ product.get_offer_type_display }}</p>
                </div>
                <div class="price">
                    <p>{{ product.area }} {{ product.get_area_unit_type_display }}</p>
                </div>
                <div class="price">
                    <p>{{ product.price }} {{ product.currency_type }}</p>
                </div>
            </div><br>
        {% endfor %}
    </ul>
</div>

<div class="pagination">
  <span class="step-links">
    {% if products.has_previous %}
    <a href="?page={{ products.previous_page_number }}{% for key,value in request.GET.items %}{% ifnotequal key 'page' %}&{{ key }}={{ value }}{% endifnotequal %}{% endfor %}">previous</a>
    {% endif %}

    <span class="current">
      Page {{ products.number }} of {{ products.paginator.num_pages }}.
    </span>

    {% if products.has_next %}
    <a href="?page={{ products.next_page_number }}{% for key,value in request.GET.items %}{% ifnotequal key 'page' %}&{{ key }}={{ value }}{% endifnotequal %}{% endfor %}">next</a>
    {% endif %}
  </span>
</div>
<br>


{% endblock %}

shop/templates/shop/product_detail.html
{% extends 'shop/base.html' %}

{% load staticfiles %}
{% load static %}

{% block title %}
  Об'єкт - "{{ object }}"
{% endblock %}


{% block content %}
    <div id="sidebar" class="col-sm-3">
        <h3>{{ object.title }}</h3><br>
        Фотографії<br>
        {% if image_models %}
            {% for image_model in image_models %}
                <div class="imgBlock">
                        <img src="{{ image_model.image.url }}" height="200" width="200" alt="">
                </div>
            {% endfor %}
        {% endif %}
        Дата публікації: {{ object.pub_date }} <br>
        ID об'єкту: {{ object.id }} <br>
        Вартість: {{ object.price }} {{ object.get_currency_type_display }} <br>
        Площа: {{ object.area }} {{ object.get_area_unit_type_display }} <br>
        Тип оголошення: {{ object.get_offer_type_display }} <br>
        Тип об'єкту: {{ object.get_object_type_display }}<br>
        Область: {{ object.region }}<br>
        Місто: {{ object.city }}<br>
        Вулиця: {{ object.address }}<br>
        Додаткова інформація: {{ object.about }}<br>
        <br>Карта:<br>
        {{form.media}}<br>
        {{form.as_p}}<br>
    </div>
{% endblock %}